model:
  base_learning_rate: 4.5e-6
  target: taming.models.multiscale_ae.MultiScaleAEModel
  params:
    # embed_dim: 256
    # n_embed: 1024
    ddconfig:
      z_channels: 32
      # resolution: 256
      in_channels: 3
      # out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      # attn_resolutions: [16]
      using_sa: true
      using_mid_sa: true
      dropout: 0.0
    aeconfig:
      beta: 0.25
      conv_ks: 3
      share_resi_ratio: 4
      resi_ratio: 0.5
      v_patch_nums: [1, 2, 3, 4, 5, 6, 8]

    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 2000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 4
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /om/user/sophiejg/project/diffVAR/mit6.S982/projects/diffusion_AR/cifar10_imagenet_format/cifar10_train.txt
        size: 32
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /om/user/sophiejg/project/diffVAR/mit6.S982/projects/diffusion_AR/cifar10_imagenet_format/cifar10_val.txt
        size: 32




